Added docker/docker-compose refactored files
elifesciences/pattern-library pull request #1200
Opened 2022-11-10 23:34 UTC by achirazi

More testing needed here until final merge. 

Still working on testing local Jenkins enclosed environment.

2023-01-15 15:58 UTC, achirazi commented
> looking at the broken build, I can see it's dying on the `smoke-tests` stage.
> 
> the Jenkinsfile says the smoke tests are executed with:
> 
> ```
> dockerComposeSmokeTests
> ```
> 
> which can be found here:
> 
> * https://github.com/elifesciences/elife-jenkins-workflow-libs/blob/master/vars/dockerComposeSmokeTests.txt
> * https://github.com/elifesciences/elife-jenkins-workflow-libs/blob/master/vars/dockerComposeSmokeTests.groovy
> 
> I was able to locally recreate the error you're seeing:
> 
> ```
> $ IMAGE_TAG=0c332a3e9fed279b6942b23f433c6a187866b374 docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec -T ci ./smoke_tests.sh ui http
> service "ci" is not running container #1
> ```
> 
> however there is no pattern-library `ci` service running, just a near-empty 'pattern-library' (`pattern-library_pattern-library`).
> 
> nor is there a hostname `ui`. It doesn't appear in my `docker network ls`, just `pattern-library_default`.
> 
> looking at a previous successful build for `pattern-library`, I should expect to see a `pattern-library_ci` available for the above command to work.
> 
> from your changes it looks like a `Dockerfile.ci` file containing the smoke tests to be run has been deleted.
> 
> I haven't scrutinised your changes closely to figure out their intent, but if you want a green build then I recommend restoring whatever is creating the `ci` service so the smoke tests can be executed.

I fixed this, but I'm a bit blocked regarding the pipelines. I am trying to understand from where is Jenkins pulling the build images. 

I tried to add `docker images ls` to see what images does it recognize, but it won't find any for some reason
https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fpattern-library/detail/PR-1200/27/pipeline
This passed only because it was pulling the latest image available on Docker Hub, but there were to images found.

Another thing I'm trying to understand is why the same Jenkinsfile passed for once then failed 
 - https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fpattern-library/detail/PR-1200/32/pipeline/ (Passed)
 - https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fpattern-library/detail/PR-1200/33/pipeline (Failed)

Can I have your opinion on this please? @lsh-0

2023-01-16 07:55 UTC, lsh-0 commented
hi @achirazi , review request received, however I won't be able to get to it until tomorrow at the earliest and it's my Mon evening already.

2023-01-17 04:44 UTC, lsh-0 commented
> I'm a bit blocked regarding the pipelines. I am trying to understand from where is Jenkins pulling the build images.

[This](https://github.com/elifesciences/pattern-library/blob/794a1222b4c830587f89a471eaf2606932c3fc86/Jenkinsfile#L16):

    sh "DESCRIPTION='${description}' docker-compose -f docker-compose.yml build"

will build the image *locally* on whatever Jenkins node is running the pipeline. Looking at `docker-compose.yml`, it is creating the images:

* elifesciences/pattern-library_assets:${IMAGE_TAG}
* elifesciences/pattern-library:${IMAGE_TAG}
* elifesciences/pattern-library_ci:${IMAGE_TAG}
* elifescience/pattern-library_selenium:${IMAGE_TAG}

[This](https://github.com/elifesciences/pattern-library/blob/794a1222b4c830587f89a471eaf2606932c3fc86/Jenkinsfile#L17):

    assetsImage = new DockerImage(this, "pattern-library_assets", "latest") 

(previously this:)

    assetsImage = new DockerImage(this, "pattern-library_assets", commit)

is getting a handle on this image:

* elifesciences/pattern-library_assets:${IMAGE_TAG}

and then for pull requests, like this one, [this](https://github.com/elifesciences/pattern-library/blob/794a1222b4c830587f89a471eaf2606932c3fc86/Jenkinsfile#L20):

    assetsImage.renameAndTag("elifesciences/pattern-library_assets","pr-${prNumber}").push()

is just tagging `elifesciences/pattern-library_assets:${IMAGE_TAG}` with `pr-${prNumber}:${IMAGE_TAG}` and then pushing it to dockerhub. It doesn't appear to be doing any renaming at all. 

This is the "`Docker`" logic that the Jenkinsfile is using: 
https://github.com/elifesciences/elife-jenkins-workflow-libs/blob/master/src/DockerImage.groovy

And we can see these tagged images on dockerhub here: 
https://hub.docker.com/r/elifesciences/pattern-library_assets/tags

Does this help with where the build images are coming from?

> I tried to add docker images ls to see what images does it recognize, but it won't find any for some reason

You probably want `docker images`. Adding `ls` to the end of the command will make it filter by repository:

    $ docker help images

    Usage:  docker images [OPTIONS] [REPOSITORY[:TAG]]

    List images

    Options:
      -a, --all             Show all images (default hides intermediate images)
          --digests         Show digests
      -f, --filter filter   Filter output based on conditions provided
          --format string   Pretty-print images using a Go template
          --no-trunc        Don't truncate output
      -q, --quiet           Only show image IDs

I appreciate that `docker network` *does* support `ls`, but `images` does not.

> Another thing I'm trying to understand is why the same Jenkinsfile passed for once then failed

Passing (32):
https://github.com/elifesciences/pattern-library/pull/1200/commits/62486e05379d5e52eacdd962d30a9a12159f009c
https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fpattern-library/detail/PR-1200/32/pipeline/

Failing (33):
https://github.com/elifesciences/pattern-library/pull/1200/commits/794a1222b4c830587f89a471eaf2606932c3fc86
https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fpattern-library/detail/PR-1200/33/pipeline/

If you look at the error message that Docker is giving you:

    [2023-01-13T09:43:17.259Z] + docker run -d elifesciences/pattern-library:794a1222b4c830587f89a471eaf2606932c3fc86
    [2023-01-13T09:43:17.259Z] Unable to find image 'elifesciences/pattern-library:794a1222b4c830587f89a471eaf2606932c3fc86' locally
    [2023-01-13T09:43:17.259Z] docker: Error response from daemon: manifest for elifesciences/pattern-library:794a1222b4c830587f89a471eaf2606932c3fc86 not found: manifest unknown: manifest unknown.
    [2023-01-13T09:43:17.259Z] See 'docker run --help'.
    script returned exit code 125

It's saying it can't find `elifesciences/pattern-library:794a1222b4c830587f89a471eaf2606932c3fc86`. This is because you changed `commit` to `"latest"`, so the image with the `commit` value wasn't built, which when referenced later in the pipeline [here](https://github.com/elifesciences/pattern-library/blob/794a1222b4c830587f89a471eaf2606932c3fc86/Jenkinsfile#L46):

    def container = sh(script: "docker run -d elifesciences/pattern-library:${commit}", returnStdout: true).trim()

will fail.

2023-01-17 12:02 UTC, achirazi commented
@lsh-0 @scottaubrey Let me know if you're happy with the changes and if it can be merged.

2023-01-18 00:05 UTC, lsh-0 commented
> @lsh-0 @scottaubrey Let me know if you're happy with the changes and if it can be merged.

Can I get a link to the ticket for this PR? I can't approve this until I have time to understand it's intent, the changes and their ramifications.

That said, I don't think `pattern-library` affects the journal infrastructure in terms of ci/end2end/prod etc, so if the [project maintainers](https://github.com/elifesciences/pattern-library/blob/develop/maintainers.txt) are happy this PR does what they want and they give their thumbs up, then that should be all you need.

2023-01-18 07:39 UTC, achirazi commented
https://github.com/elifesciences/issues/issues/7664 @lsh-0

2023-01-18 07:40 UTC, achirazi commented
> That said, I don't think `pattern-library` affects the journal infrastructure in terms of ci/end2end/prod etc, so if the [project maintainers](https://github.com/elifesciences/pattern-library/blob/develop/maintainers.txt) are happy this PR does what they want and they give their thumbs up, then that should be all you need.

@nlisgo @discodavey

2023-01-18 08:45 UTC, scottaubrey requested changes
I've pulled down the changes, and they seem to mostly work fine.

The `bin/watch` functionality is broken, and might need a little bit of rethinking of the services to restore it. After just correcting service names, the error I get is:
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "php": executable file not found in $PATH: unknown
```
The `ui` service being a mostly empty nginx container with the static files, this makes sense, but maybe we need an additional service defined, say in `docker-compose.override.yml` for the entrypoints into the builder containers.

Finally, I've tried to run as many of the README commands as I can, but many of the commands running on the host didn't work. I'm not sure may of them are related to this PR, but thought it worth saying anyway - pattern-library documentation seems a bit broken with my modern mac.

2023-01-18 08:45 UTC, scottaubrey commented on Dockerfile
> +FROM assets_builder
Lines that take a FROM, but don't add any other layers or commands, don't actually do anything and can be removed

2023-01-23 08:53 UTC, scottaubrey commented
Thanks @achirazi - the commands now run, though I can't tell what they do - I changes some files but there was no further output on the console, and I couldn't see changes reflected in the browser. However, I don't know what I'm doing, so acceptance of this is now over to @discodavey or @nlisgo to validate it does work.

2023-01-23 12:49 UTC, discodavey commented
Just tested this and all is ok but I did have a issue at the beginning where it said the port was already being used. Maybe we could put in about using ```docker-compose down --volumes --remove-orphans``` before running docker-compose build.

Also, having docker-compose build and up as one would be helpful rather than having to run them separately.

Just an opinion.

2023-01-25 07:39 UTC, achirazi commented
@discodavey I just updated the README. Let me know if you're happy with the changes.

2025-02-06 07:41 UTC, closed without merging