Add Related item to Aside component
elifesciences/pattern-library pull request #1222
Opened 2023-01-19 15:25 UTC by viktoria-mahmud

2023-01-19 16:08 UTC, nlisgo approved these changes

2023-01-19 16:08 UTC, nlisgo commented on source/_patterns/02-organisms/components/content-aside~complete.json
> +        "url": null,
must be a string so replace with `"#"`

2023-01-19 16:08 UTC, nlisgo requested changes
See my comment about url

2023-01-19 16:19 UTC, viktoria-mahmud commented on source/_patterns/02-organisms/components/content-aside~complete.json
> +        "url": null,
Thanks, it is fixed now.

2023-01-20 08:48 UTC, nlisgo approved these changes

2023-01-20 09:59 UTC, Cosmin-Daniel approved these changes

2023-01-20 10:38 UTC, merged